### ISSUE TITLE
services not flagging up

### ISSUE THREAD

**Issue by biohazd** [saz/Naglite3#17]
Hi

I have services that are showing as "critical"  and flagged up on Nagios, but they don't show on Naglite3 dashboard under "Service Status" .  They are simply shown under "Notification" heading.  The servcie status is then reporting "ALL MONITORED SERVICES OK"

Hosts are showing up correctly as critical.

![nag-alert](https://cloud.githubusercontent.com/assets/986551/22027557/268f3380-dccc-11e6-80db-10fe4f0aae8c.png)

**Comment by biohazd** [comment]
I think it might relate to notifications being off:
notification_options    n
notifications_enabled   0

**Comment by saz** [comment]
That's right. If a service has notifications disabled, it will only be listed under notifications, as you (or at least I think like that) don't want information of service states (OK, Critical,...)

But this should also be true for hosts with disabled notifications.

**Comment by biohazd** [comment]
Can you show me how to override that, I don't care if notifications are on or off, I still want the services to flag up as critical.  (I did read the index.php, but can't figure out the bit I need to change)

Also, thanks for replying so quickly !!

**Comment by saz** [comment]
Right now, there is no way of chaning this behavior.
Out of curiosity: why are you disabling notifications for services and hosts, if you still want to be alerted, if there is an issue?

**Comment by biohazd** [comment]
I have turned on the notifications for all services now, so it should work as expected.

My setup was a bit strange, I only wanted some alerts emailed to me, I didn't want everything emailing me. It was just nice to have some things on the dashboard, more for information than for alerting.

Please close this and thanks for replying so quickly.

**Comment by saz** [comment]
Sometimes things need to be a little strange :-)

You're welcome!
