### ISSUE TITLE
Filtering

### ISSUE THREAD

**Issue by nimeshc64** [saz/Naglite3#18]
How to filter by hostgroup-name ,  only i want to show given hostgroup service and host only

**Comment by andreasbalevik** [comment]
This is a feature i would like to see too.

I have some ideas. One of them is generating different status.dat files based on the hostgroup file in nagios. Different paths show different status.dat data. Eksample /hostgroup1 /hostgroup2 etc. Navigate with a drop-down list or something.

Either way i think the connection between hosts and hostsgroup is in the hostgroup.cfg file used to configure Nagios. And the status.dat file contains only hostname i think.

I hope someone looks into this. And if i find a good solution maybe i will make a pull request.

/Andreas

**Comment by saz** [comment]
I'm open to any pull request, to add filter options.
